services:
  app:
    build: .
    container_name: auth-service-app
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      DB_URL: jdbc:mysql://172.17.0.1:3306/auth_service_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
